name: Docker 镜像构建

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: demo-fastapi-backend

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 登录阿里云容器镜像服务
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ALIYUN_REGISTRY }}
        username: ${{ secrets.ALIYUN_REGISTRY_USER }}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 缓存 Docker 层
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache-backend
        key: ${{ runner.os }}-buildx-backend-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-backend-

    - name: 获取版本号
      id: version
      run: echo "VERSION=$(date +%Y%m%d)-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

    - name: 构建并推送后端镜像
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ env.IMAGE_NAME }}:latest
          ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
        cache-from: type=local,src=/tmp/.buildx-cache-backend
        cache-to: type=local,dest=/tmp/.buildx-cache-backend-new,mode=max

    - name: 更新后端缓存
      run: |
        rm -rf /tmp/.buildx-cache-backend
        mv /tmp/.buildx-cache-backend-new /tmp/.buildx-cache-backend

  build-frontend:
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: demo-fastapi-frontend

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 登录阿里云容器镜像服务
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ALIYUN_REGISTRY }}
        username: ${{ secrets.ALIYUN_REGISTRY_USER }}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 缓存 Docker 层
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache-frontend
        key: ${{ runner.os }}-buildx-frontend-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-frontend-

    - name: 获取版本号
      id: version
      run: echo "VERSION=$(date +%Y%m%d)-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

    - name: 构建并推送前端镜像
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: |
          ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ env.IMAGE_NAME }}:latest
          ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
        cache-from: type=local,src=/tmp/.buildx-cache-frontend
        cache-to: type=local,dest=/tmp/.buildx-cache-frontend-new,mode=max

    - name: 更新前端缓存
      run: |
        rm -rf /tmp/.buildx-cache-frontend
        mv /tmp/.buildx-cache-frontend-new /tmp/.buildx-cache-frontend 